### ISSUE TITLE
Model of Well to borehole relationship

### ISSUE THREAD

**Issue by KellyVance** [geological-survey-of-queensland/gsq-borehole-profile#2]
The image for the model describing the relationship between boreholes, wells, and wellbores is missing. 

This is required to ensure we have captured the required details for each and to be confident the modeling accurately represents the distinctions and requirements between a borehole and the interval(s) that make it up.

**Comment by nicholascar** [comment]
@KellyVance this will be part of the model that includes this model as a part of it rather than part of this simple directly. I'll come in 2 days next week and we can give the overarching Boreholes model a proper go. I've got some diagrams done already.

**Comment by DavidCrosswellGSQ** [comment]
@KellyVance I have added in the diagram [Borehole Hierarchy](https://github.com/geological-survey-of-queensland/gsq-borehole-profile/blob/master/model/borehole-hierarchy.svg)
As @nicholascar says, some further work to do on the models.
